<a href="https://colab.research.google.com/github/rakeshbanisetti/mds_lab/blob/main/week9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

csv_file_path = '/content/student_performance_dataset.csv'

try:
    # Load the CSV file into a pandas DataFrame
    student_performance_df = pd.read_csv(csv_file_path)
    print(f"Successfully loaded '{csv_file_path}' into a DataFrame with {student_performance_df.shape[0]} rows and {student_performance_df.shape[1]} columns.")

    # Display the first few rows to confirm
    print("\nFirst 5 rows of the 'student_performance_df' DataFrame:")
    display(student_performance_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found. Please ensure it is present in the specified path.")
except Exception as e:
    print(f"An error occurred while loading the CSV file: {e}")

An error occurred while loading the CSV file: No columns to parse from file

In [5]:
csv_file_path = '/content/student_performance_dataset.csv'

try:
    with open(csv_file_path, 'r') as f:
        content = f.read(500) # Read the first 500 characters to inspect
    print(f"Content of '{csv_file_path}' (first 500 characters):\n---\n{content}\n---")
    if not content.strip():
        print(f"The file '{csv_file_path}' appears to be empty.")
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while trying to read the file: {e}")

Content of '/content/student_performance_dataset.csv' (first 500 characters):
---

---
The file '/content/student_performance_dataset.csv' appears to be empty.

In [9]:
import pandas as pd
import os # Import os module to check file existence

excel_file_path = '/content/research_student (1).xlsx'

# First, check if the file actually exists
if not os.path.exists(excel_file_path):
    print(f"Error: The Excel file was not found at {excel_file_path}. Please ensure it is present in the specified path.")
else:
    try:
        # Load the Excel file into a pandas DataFrame
        research_student_df = pd.read_excel(excel_file_path)
        print(f"Successfully loaded '{excel_file_path}' into a DataFrame with {research_student_df.shape[0]} rows and {research_student_df.shape[1]} columns.")

        # Display the first few rows to confirm
        print("\nFirst 5 rows of the 'research_student_df' DataFrame:")
        display(research_student_df.head())

    except Exception as e:
        print(f"An error occurred while loading the Excel file: {e}")

Error: The Excel file was not found at /content/research_student (1).xlsx. Please ensure it is present in the specified path.

In [7]:
# Check for missing values in each column
missing_values = research_student_df.isnull().sum()

# Display columns with missing values and their counts
print("Missing values in each column:")
display(missing_values[missing_values > 0])

Missing values in each column:

Branch                    3
Marks[10th]               3
Marks[12th]               3
Gender                    3
Board[10th]               3
Board[12th]               3
Category                  3
GPA 1                     3
Rank                      2
Normalized Rank           3
CGPA                      3
Current Back              3
Ever Back                 4
GPA 2                     3
GPA 3                     3
GPA 4                     3
GPA 5                     3
GPA 6                     3
Olympiads Qualified       3
Technical Projects        3
Tech Quiz                 3
Engg. Coaching            3
NTSE Scholarships         3
Miscellany Tech Events    3
dtype: int64

In [10]:
# Check if research_student_df is defined before proceeding
if 'research_student_df' in locals():
    print(f"Shape of DataFrame before dropping missing values: {research_student_df.shape}")

    # Drop rows with any missing values
    research_student_df_cleaned = research_student_df.dropna()

    print(f"Shape of DataFrame after dropping missing values: {research_student_df_cleaned.shape}")

    # Display the first few rows of the cleaned DataFrame
    print("\nFirst 5 rows of the cleaned 'research_student_df_cleaned' DataFrame:")
    display(research_student_df_cleaned.head())
else:
    print("Error: 'research_student_df' is not defined. Please ensure the Excel file was loaded successfully.")

Error: 'research_student_df' is not defined. Please ensure the Excel file was loaded successfully.

In [9]:
# Verify that there are no more missing values
missing_values_after_drop = research_student_df_cleaned.isnull().sum()

print("\nMissing values in each column after dropping rows:")
display(missing_values_after_drop[missing_values_after_drop > 0])

Missing values in each column after dropping rows:

Series([], dtype: int64)

In [10]:
branch_avg_marks = research_student_df_cleaned.groupby('Branch')[['Marks[10th]', 'Marks[12th]']].mean().reset_index()
display(branch_avg_marks)

  Branch  Marks[10th]  Marks[12th]
0  CIVIL        78.82        71.21
1    CSE        86.87        79.52
2    ECE        85.83        79.59
3    EEE        83.64        77.73
4     IT        86.04        77.83
5   MECH        81.59        78.04
6   PROD        83.47        73.37

In [11]:
marks_10th_above_85 = research_student_df_cleaned[research_student_df_cleaned['Marks[10th]'] > 85]
print(f"Number of students with 10th marks above 85: {marks_10th_above_85.shape[0]}")
print("\nStudents with 'Marks[10th]' greater than 85:")
display(marks_10th_above_85.head())

Number of students with 10th marks above 85: 122

Students with 'Marks[10th]' greater than 85:

,Branch,Marks[10th],Marks[12th],Gender,Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,CGPA,Current Back,Ever Back,GPA 2,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events
2,CSE,86.40,71.80,Male,CBSE,CBSE,GEN,6.47,24222.00,8.65,6.10,1.00,7.00,6.12,5.88,5.53,6.44,6.19,2.00,2.00,0.00,1.00,0.00,4.00
3,CSE,88.14,78.00,Male,ICSE,ICSE,GEN,7.35,24723.00,8.83,6.65,1.00,1.00,6.35,6.54,6.41,6.50,6.69,1.00,1.00,3.00,0.00,0.00,5.00
11,EEE,89.60,80.20,Male,C.B.S.E,C.B.S.E,GEN,6.53,29445.00,10.52,6.23,1.00,1.00,6.35,6.36,6.41,5.50,5.69,6.00,3.00,3.00,6.00,0.00,5.00
12,EEE,90.40,65.40,Male,CBSE,CBSE,GEN,6.65,28051.00,10.02,6.27,1.00,9.00,6.00,6.59,6.12,5.88,6.38,5.00,1.00,4.00,5.00,0.00,5.00
23,CIVIL,88.60,71.80,Male,C.B.S.E.,C.B.S.E,OBC,6.29,59417.00,21.22,6.71,0.00,0.00,6.53,6.24,7.18,7.25,7.06,0.00,0.00,0.00,0.00,0.00,5.00

In [12]:
average_gpa_for_high_achievers = marks_10th_above_85['CGPA'].mean()
print(f"The average CGPA for students with 'Marks[10th]' above 85 is: {average_gpa_for_high_achievers:.2f}")

The average CGPA for students with 'Marks[10th]' above 85 is: 7.43

In [13]:
# Identify categorical columns
categorical_cols = research_student_df_cleaned.select_dtypes(include=['object', 'category']).columns

print(f"Categorical columns identified: {list(categorical_cols)}")

# Apply one-hot encoding to create a new DataFrame
research_student_df_encoded = pd.get_dummies(research_student_df_cleaned, columns=categorical_cols, drop_first=True)

print(f"\nShape of the original DataFrame: {research_student_df_cleaned.shape}")
print(f"Shape of the encoded DataFrame: {research_student_df_encoded.shape}")

print("\nFirst 5 rows of the encoded 'research_student_df_encoded' DataFrame:")
display(research_student_df_encoded.head())

Categorical columns identified: ['Branch', 'Gender', 'Board[10th]', 'Board[12th]', 'Category']

Shape of the original DataFrame: (219, 24)
Shape of the encoded DataFrame: (219, 114)

First 5 rows of the encoded 'research_student_df_encoded' DataFrame:

,Marks[10th],Marks[12th],GPA 1,Rank,Normalized Rank,CGPA,Current Back,Ever Back,GPA 2,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events,Branch_CSE,Branch_ECE,Branch_EEE,Branch_IT,Branch_MECH,Branch_PROD,Gender_Male,Board[10th]_B.S.E.B PATNA,Board[10th]_B.S.E.B(PATNA),Board[10th]_B.S.E.B.PATNA,Board[10th]_BIHAR BOARD,Board[10th]_BIHAR SCHOOL EXAMINATION BOARD PATNA,"Board[10th]_BIHAR SCHOOL EXAMINATION BOARD, PATNA","Board[10th]_BIHAR SCHOOL EXAMINATION BOARD,PATNA","Board[10th]_BOARD OF SECONDARY EDUCATION,ANDHRA PRADESH",Board[10th]_BSEB,Board[10th]_BSEB PATNA,Board[10th]_BSEB Patna,Board[10th]_Bihar Board,"Board[10th]_Bihar School ExaminatiAon Board, Patna","Board[10th]_Bihar Shool Examination Board ,Patna",Board[10th]_Board of Secondary Education,Board[10th]_C.B.S.E,Board[10th]_C.B.S.E.,Board[10th]_CBSE,Board[10th]_CBSE BOARD,Board[10th]_CENTRAL BOARD OF SECONDARY EDUCATION,Board[10th]_Central Board of Secondary Education,Board[10th]_Haryana Board,Board[10th]_I.C.S.E,Board[10th]_I.C.S.E.,Board[10th]_ICSE,Board[10th]_ISCE,Board[10th]_MAHARASHTRA STATE BOARD OF SECONDARY EDUCATION,Board[10th]_Maharashtra State Board,Board[10th]_RAJASTHAN BOARD,Board[10th]_RBSE,Board[10th]_Rajasthan Board,Board[10th]_STATE BOARD,Board[10th]_STATE BOARD OF ANDHRA PRADESH,Board[10th]_U.P. BOARD,Board[10th]_UP BOARD,Board[10th]_Uttar Pradesh Board,Board[10th]_bihar school examination board,Board[10th]_cbse,Board[10th]_i.c.s.e,Board[12th]_B.S.E.B,Board[12th]_B.S.E.B(H.S.PATNA),Board[12th]_B.S.E.B.PATNA,Board[12th]_BIHAR BOARD,"Board[12th]_BIHAR SCHOOL EXAMINATION BOARD, PATNA","Board[12th]_BIHAR SCHOOL EXAMINATION BOARD,PATNA","Board[12th]_BOARD OF INTERMEDIATE EDUCATION,ANDHRA PRADESH","Board[12th]_BOARD OF SECONDARY EDUCATION, RAJASTHAN",Board[12th]_BSEB,Board[12th]_BSEB PATNA,Board[12th]_BSEB Patna,Board[12th]_Bihar Board,"Board[12th]_Bihar School ExaminatiAon Board, Patna","Board[12th]_Bihar School Examination Board ,Patna","Board[12th]_Boar of Intermediate Education, A.P.",Board[12th]_Board of Intermediate Education Andhra Pradesh,Board[12th]_C.B.S.E,Board[12th]_C.B.S.E.,Board[12th]_CBSE,Board[12th]_CBSE BOARD,Board[12th]_CBSE Board,Board[12th]_CENTRAL BOARD OF SECONDARY EDUCATION,Board[12th]_Central Board,Board[12th]_Central Board of Secondary Education,Board[12th]_Goa Board for Secondary and Higher Secondary Education,Board[12th]_H.S.E.B,Board[12th]_I Sc,Board[12th]_I.S.C,Board[12th]_ICSE,Board[12th]_INTERMEDIATE BOARD OF EDUCATION- ANDHRA PRADESH,Board[12th]_ISC,Board[12th]_ISCE,Board[12th]_Maharashtra State Board,Board[12th]_NIOS,Board[12th]_NIOS BOARD,Board[12th]_RAJASTHAN BOARD,Board[12th]_RBSE,Board[12th]_STATE BOARD,Board[12th]_STATE BOARD OF ANDHRA PRADESH,Board[12th]_U.P. BOARD,Board[12th]_UP BOARD,Board[12th]_bhopal,Board[12th]_bihar school examination board,Board[12th]_c.b.s.e,Board[12th]_cbse,Board[12th]_state,Category_OBC,Category_SC,Category_ST
1,77.57,64.60,6.29,44718.00,15.97,6.02,1.00,4.00,6.12,5.94,5.41,6.25,6.13,1.00,4.00,3.00,2.00,0.00,5.00,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,86.40,71.80,6.47,24222.00,8.65,6.10,1.00,7.00,6.12,5.88,5.53,6.44,6.19,2.00,2.00,0.00,1.00,0.00,4.00,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,88.14,78.00,7.35,24723.00,8.83,6.65,1.00,1.00,6.35,6.54,6.41,6.50,6.69,1.00,1.00,3.00,0.00,0.00,5.00,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,65.40,59.80,6.41,232157.00,82.91,6.09,1.00,11.00,6.00,5.71,5.24,5.88,6.25,2.00,0.00,2.00,2.00,0.00,1.00,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
5,81.00,74.00,6.80,23252.00,8.30,6.13,1.00,0.00,6.06,5.88,6.00,5.93,5.44,2.00,0.00,2.00,2.00,0.00,1.00,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [1]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Student': [f'S{i}' for i in range(1, 16)],
    'Score': [65, 72, 88, 55, 91, 78, 62, 85, 70, 95, 60, 75, 80, 50, 99]
}
df_scores = pd.DataFrame(data)

print("Original DataFrame with Scores:")
display(df_scores)

# Apply pd.cut() to create 3 equal-width bins
df_scores['Score_Category_Cut'] = pd.cut(
    df_scores['Score'],
    bins=3,
    labels=['Low', 'Medium', 'High'],
    include_lowest=True
)

print("\nDataFrame after applying pd.cut() (Equal-Width Bins):")
display(df_scores.head())

print("\nValue counts for Score_Category_Cut:")
display(df_scores['Score_Category_Cut'].value_counts().sort_index())

Original DataFrame with Scores:

   Student  Score
0       S1     65
1       S2     72
2       S3     88
3       S4     55
4       S5     91
5       S6     78
6       S7     62
7       S8     85
8       S9     70
9      S10     95
10     S11     60
11     S12     75
12     S13     80
13     S14     50
14     S15     99

DataFrame after applying pd.cut() (Equal-Width Bins):

  Student  Score Score_Category_Cut
0      S1     65                Low
1      S2     72             Medium
2      S3     88               High
3      S4     55                Low
4      S5     91               High

Value counts for Score_Category_Cut:

Score_Category_Cut
Low       5
Medium    5
High      5
Name: count, dtype: int64

**`pd.qcut()` (Equal-Depth Bins / Quantile-Based Bins)**

*   **Purpose**: `pd.qcut()` is used to segment data into bins such that **each bin has roughly the same number of observations (or the same quantile range)**. It determines bin edges based on the quantiles of the data.
*   **Use Case**: Ideal when you want to create groups with an approximately equal number of members, regardless of the numerical range they cover. For example, dividing students into 'Bottom 25%', 'Middle 50%', 'Top 25%' based on their scores.
*   **Disadvantage**: The bin widths can vary significantly, especially with skewed data, which might make the bin ranges less intuitive or interpretable compared to `pd.cut()`.

**Example for `pd.qcut()`:** Now, let's use `pd.qcut()` on the same 'Score' column to create three bins, each containing approximately the same number of students.

In [2]:
import pandas as pd
import numpy as np

# Using the same df_scores DataFrame from the previous example
# Apply pd.qcut() to create 3 equal-depth bins
df_scores['Score_Category_Qcut'] = pd.qcut(
    df_scores['Score'],
    q=3,
    labels=['Bottom', 'Middle', 'Top'],
    duplicates='drop' # Handle cases where quantile edges are not unique
)

print("DataFrame after applying pd.qcut() (Equal-Depth Bins):")
display(df_scores.head())

print("\nValue counts for Score_Category_Qcut:")
display(df_scores['Score_Category_Qcut'].value_counts().sort_index())

DataFrame after applying pd.qcut() (Equal-Depth Bins):

  Student  Score Score_Category_Cut Score_Category_Qcut
0      S1     65                Low              Bottom
1      S2     72             Medium              Middle
2      S3     88               High                 Top
3      S4     55                Low              Bottom
4      S5     91               High                 Top

Value counts for Score_Category_Qcut:

Score_Category_Qcut
Bottom    5
Middle    5
Top       5
Name: count, dtype: int64

### Key Differences Summarized:

*   **`pd.cut()`**: Creates bins of **equal *width* (range)**. The number of data points in each bin can vary greatly.
*   **`pd.qcut()`**: Creates bins of **equal *depth* (number of observations)**. The width of each bin can vary greatly.

Choose `pd.cut()` when you have specific, meaningful ranges you want to define. Choose `pd.qcut()` when you want to ensure an even distribution of data points across your bins, regardless of the numerical range they span.

### Re-loading and Cleaning Data for `loc` and `iloc` Demonstrations

Given that the Excel file `/content/research_student (1).xlsx` is now available, I will re-load the data and perform the cleaning steps to ensure `research_student_df_cleaned` is correctly defined for the following `loc` and `iloc` operations.

In [13]:
import pandas as pd

excel_file_path = '/content/research_student (1).xlsx'

try:
    # Load the Excel file into a pandas DataFrame
    research_student_df = pd.read_excel(excel_file_path)
    print(f"Successfully loaded '{excel_file_path}' into a DataFrame with {research_student_df.shape[0]} rows and {research_student_df.shape[1]} columns.")

    # Display the first few rows to confirm
    print("\nFirst 5 rows of the 'research_student_df' DataFrame:")
    display(research_student_df.head())

except Exception as e:
    print(f"An error occurred while loading the Excel file: {e}")

Successfully loaded '/content/research_student (1).xlsx' into a DataFrame with 223 rows and 24 columns.

First 5 rows of the 'research_student_df' DataFrame:

,Branch,Marks[10th],Marks[12th],Gender,Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,...,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CIVIL,77.57,64.6,Male,BSEB Patna,BSEB Patna,OBC,6.29,44718.0,15.970714,...,5.94,5.41,6.25,6.13,1.0,4.0,3.0,2.0,0.0,5.0
2,CSE,86.40,71.8,Male,CBSE,CBSE,GEN,6.47,24222.0,8.650714,...,5.88,5.53,6.44,6.19,2.0,2.0,0.0,1.0,0.0,4.0
3,CSE,88.14,78.0,Male,ICSE,ICSE,GEN,7.35,24723.0,8.829643,...,6.54,6.41,6.50,6.69,1.0,1.0,3.0,0.0,0.0,5.0
4,CSE,65.40,59.8,Female,CBSE,CBSE,ST,6.41,232157.0,82.913214,...,5.71,5.24,5.88,6.25,2.0,0.0,2.0,2.0,0.0,1.0

In [14]:
# Drop rows with any missing values to create the cleaned DataFrame
research_student_df_cleaned = research_student_df.dropna()

print(f"Shape of DataFrame before dropping missing values: {research_student_df.shape}")
print(f"Shape of DataFrame after dropping missing values: {research_student_df_cleaned.shape}")

print("\nFirst 5 rows of the cleaned 'research_student_df_cleaned' DataFrame:")
display(research_student_df_cleaned.head())

Shape of DataFrame before dropping missing values: (223, 24)
Shape of DataFrame after dropping missing values: (219, 24)

First 5 rows of the cleaned 'research_student_df_cleaned' DataFrame:

,Branch,Marks[10th],Marks[12th],Gender,Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,...,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events
1,CIVIL,77.57,64.6,Male,BSEB Patna,BSEB Patna,OBC,6.29,44718.0,15.970714,...,5.94,5.41,6.25,6.13,1.0,4.0,3.0,2.0,0.0,5.0
2,CSE,86.40,71.8,Male,CBSE,CBSE,GEN,6.47,24222.0,8.650714,...,5.88,5.53,6.44,6.19,2.0,2.0,0.0,1.0,0.0,4.0
3,CSE,88.14,78.0,Male,ICSE,ICSE,GEN,7.35,24723.0,8.829643,...,6.54,6.41,6.50,6.69,1.0,1.0,3.0,0.0,0.0,5.0
4,CSE,65.40,59.8,Female,CBSE,CBSE,ST,6.41,232157.0,82.913214,...,5.71,5.24,5.88,6.25,2.0,0.0,2.0,2.0,0.0,1.0
5,CSE,81.00,74.0,Male,CBSE,CBSE,GEN,6.80,23252.0,8.304286,...,5.88,6.00,5.93,5.44,2.0,0.0,2.0,2.0,0.0,1.0

### Demonstrating `loc` operations

`loc` is primarily label-based, meaning you use the actual row and column labels to select data. It can also take a boolean array.

In [15]:
# Select a single row by its index label (e.g., the first row, which has index 1 after cleaning)
print("\n--- Using loc to select a single row (index 1) ---")
display(research_student_df_cleaned.loc[1])

# Select multiple rows by their index labels and specific columns
print("\n--- Using loc to select rows 2, 3, and columns 'Branch', 'Marks[10th]' ---")
display(research_student_df_cleaned.loc[[2, 3], ['Branch', 'Marks[10th]']])

# Select a slice of rows and all columns
print("\n--- Using loc to select a slice of rows (from index 5 to 7, inclusive) and all columns ---")
display(research_student_df_cleaned.loc[5:7, :])

# Select rows based on a boolean condition and specific columns
print("\n--- Using loc with a boolean condition (Marks[10th] > 90) and columns 'Branch', 'Marks[10th]', 'Marks[12th]' ---")
display(research_student_df_cleaned.loc[research_student_df_cleaned['Marks[10th]'] > 90, ['Branch', 'Marks[10th]', 'Marks[12th]']].head())

--- Using loc to select a single row (index 1) ---

Branch                         CIVIL
Marks[10th]                    77.57
Marks[12th]                     64.6
Gender                          Male
Board[10th]               BSEB Patna
Board[12th]               BSEB Patna
Category                         OBC
GPA 1                           6.29
Rank                         44718.0
Normalized Rank            15.970714
CGPA                            6.02
Current Back                     1.0
Ever Back                        4.0
GPA 2                           6.12
GPA 3                           5.94
GPA 4                           5.41
GPA 5                           6.25
GPA 6                           6.13
Olympiads Qualified              1.0
Technical Projects               4.0
Tech Quiz                        3.0
Engg. Coaching                   2.0
NTSE Scholarships                0.0
Miscellany Tech Events           5.0
Name: 1, dtype: object

--- Using loc to select rows 2, 3, and columns 'Branch', 'Marks[10th]' ---

  Branch  Marks[10th]
2    CSE        86.40
3    CSE        88.14

--- Using loc to select a slice of rows (from index 5 to 7, inclusive) and all columns ---

,Branch,Marks[10th],Marks[12th],Gender,Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,...,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events
5,CSE,81.0,74.0,Male,CBSE,CBSE,GEN,6.80,23252.0,8.304286,...,5.88,6.00,5.93,5.44,2.0,0.0,2.0,2.0,0.0,1.0
6,ECE,74.4,82.0,Male,BSEB,CBSE,GEN,6.88,23257.0,8.306071,...,6.35,5.94,5.88,4.56,2.0,0.0,1.0,0.0,2.0,3.0
7,ECE,83.8,73.0,Female,C.B.S.E,C.B.S.E,SC,7.24,103217.0,36.863214,...,6.29,6.12,7.00,7.00,3.0,2.0,1.0,3.0,0.0,3.0

--- Using loc with a boolean condition (Marks[10th] > 90) and columns 'Branch', 'Marks[10th]', 'Marks[12th]' ---

   Branch  Marks[10th]  Marks[12th]
12    EEE        90.40         65.4
28  CIVIL        91.67         70.6
31  CIVIL        93.40         63.0
34  CIVIL        93.00         80.0
37    CSE        92.83         82.4

### Demonstrating `iloc` operations

`iloc` is primarily integer-position-based, meaning you use the numerical position (from 0 to N-1) of rows and columns to select data.

In [16]:
# Select a single row by its integer position (e.g., the first row, at position 0)
print("\n--- Using iloc to select a single row (position 0) ---")
display(research_student_df_cleaned.iloc[0])

# Select multiple rows by their integer positions and specific columns by integer positions
print("\n--- Using iloc to select rows at positions 1, 2 and columns at positions 0 (Branch), 1 (Marks[10th]) ---")
display(research_student_df_cleaned.iloc[[1, 2], [0, 1]])

# Select a slice of rows and all columns
print("\n--- Using iloc to select a slice of rows (from position 4 up to, but not including, 7) and all columns ---")
display(research_student_df_cleaned.iloc[4:7, :])

# Select all rows and a slice of columns (e.g., the first 3 columns)
print("\n--- Using iloc to select all rows and a slice of columns (first 3 columns) ---")
display(research_student_df_cleaned.iloc[:, 0:3].head())

--- Using iloc to select a single row (position 0) ---

Branch                         CIVIL
Marks[10th]                    77.57
Marks[12th]                     64.6
Gender                          Male
Board[10th]               BSEB Patna
Board[12th]               BSEB Patna
Category                         OBC
GPA 1                           6.29
Rank                         44718.0
Normalized Rank            15.970714
CGPA                            6.02
Current Back                     1.0
Ever Back                        4.0
GPA 2                           6.12
GPA 3                           5.94
GPA 4                           5.41
GPA 5                           6.25
GPA 6                           6.13
Olympiads Qualified              1.0
Technical Projects               4.0
Tech Quiz                        3.0
Engg. Coaching                   2.0
NTSE Scholarships                0.0
Miscellany Tech Events           5.0
Name: 1, dtype: object

--- Using iloc to select rows at positions 1, 2 and columns at positions 0 (Branch), 1 (Marks[10th]) ---

  Branch  Marks[10th]
2    CSE        86.40
3    CSE        88.14

--- Using iloc to select a slice of rows (from position 4 up to, but not including, 7) and all columns ---

,Branch,Marks[10th],Marks[12th],Gender,Board[10th],Board[12th],Category,GPA 1,Rank,Normalized Rank,...,GPA 3,GPA 4,GPA 5,GPA 6,Olympiads Qualified,Technical Projects,Tech Quiz,Engg. Coaching,NTSE Scholarships,Miscellany Tech Events
5,CSE,81.0,74.0,Male,CBSE,CBSE,GEN,6.80,23252.0,8.304286,...,5.88,6.00,5.93,5.44,2.0,0.0,2.0,2.0,0.0,1.0
6,ECE,74.4,82.0,Male,BSEB,CBSE,GEN,6.88,23257.0,8.306071,...,6.35,5.94,5.88,4.56,2.0,0.0,1.0,0.0,2.0,3.0
7,ECE,83.8,73.0,Female,C.B.S.E,C.B.S.E,SC,7.24,103217.0,36.863214,...,6.29,6.12,7.00,7.00,3.0,2.0,1.0,3.0,0.0,3.0

--- Using iloc to select all rows and a slice of columns (first 3 columns) ---

  Branch  Marks[10th]  Marks[12th]
1  CIVIL        77.57         64.6
2    CSE        86.40         71.8
3    CSE        88.14         78.0
4    CSE        65.40         59.8
5    CSE        81.00         74.0

In [17]:
gender_avg_marks = research_student_df_cleaned.groupby('Gender')[['Marks[10th]', 'Marks[12th]']].mean().reset_index()
display(gender_avg_marks)

   Gender  Marks[10th]  Marks[12th]
0  Female    87.685652    80.702174
1    Male    83.432948    77.092543