In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
l=[1,2,3,4,5]
p=pd.Series(l)
print(p)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
import pandas as pd
import numpy as np
l=[1,2,3,4,5]
p=pd.Series(l,index=['a','b','c','d','e'])
print(p)
n=np.array(l)
print(n)
num=pd.Series(n,index=['a','b','c','d','e'])
print(num)

a    1
b    2
c    3
d    4
e    5
dtype: int64
[1 2 3 4 5]
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
import pandas as pd
d={'a':1,'b':2,'c':3,'d':4,'e':5}
p=pd.Series(d)
print(p)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
import pandas as pd
d={'a':1,'b':2,'c':3,'d':4,'e':5}
p=pd.Series(d,index=['e','d','c','b','a'])
print(p)

e    5
d    4
c    3
b    2
a    1
dtype: int64

In [12]:
import pandas as pd
d=[[1,2,3],[3,4,5],[5,6,7]]
p=pd.DataFrame(d,columns=['a','b','c'])
print(p)

   a  b  c
0  1  2  3
1  3  4  5
2  5  6  7

In [17]:
import pandas as pd
d={"Names":["Raki","Rohith","Sahil"],"Age":[24,25,26],"Salary":[50000,1000000,70000]}
p=pd.DataFrame(d)
print(p)
print("\n")
d=[["Raki","Rohith","Sahil"],[24,25,26],[50000,1000000,70000]]
p=pd.DataFrame(d,columns=["Name","Age","Salary"])
print(p)

    Names  Age  Salary
0    Raki   24   50000
1  Rohith   25   45000
2   Sahil   26   70000


    Name     Age Salary
0   Raki  Rohith  Sahil
1     24      25     26
2  50000   45000  70000

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Employee.csv to Employee.csv

Once the file is uploaded, you can then load it into a pandas DataFrame. If you have multiple files, you'll need to specify which one you want to load. For a single file, you can access its name from the `uploaded` dictionary.

In [3]:
import pandas as pd

# Assuming 'Employee.csv' is the file you just uploaded
file_name = next(iter(uploaded))
df = pd.read_csv(file_name)

print(f"Successfully loaded '{file_name}' into a DataFrame. Here are the first 5 rows:")
print(df.head())

Successfully loaded 'Employee.csv' into a DataFrame. Here are the first 5 rows:
   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1

In [19]:
import pandas as pd
df.head(10)
print("\n")
df.tail(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

In [21]:
df.shape

(4653, 9)

In [22]:
df.index

RangeIndex(start=0, stop=4653, step=1)

In [25]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [30]:
print(list(df.columns))

['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender', 'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot']

In [36]:
print(df[df['Age']>30])

      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No
2     Bachelors         2014  New Delhi            3   38  Female          No
6     Bachelors         2015  New Delhi            3   38    Male          No
7     Bachelors         2016  Bangalore            3   34  Female          No
9       Masters         2017  New Delhi            2   37    Male          No
...         ...          ...        ...          ...  ...     ...         ...
4643  Bachelors         2013  Bangalore            3   31  Female          No
4644  Bachelors         2015       Pune            3   32  Female         Yes
4645    Masters         2017       Pune            2   31  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot
0                             0           0
2                             2           0
6                             0           0
7                             2           1
9                             2           0
...                         ...         ...
4643                          5           0
4644                          1           1
4645                          2           0
4649                          2           1
4652                          4           0

[1403 rows x 9 columns]

In [40]:
df1=df.drop(columns=['LeaveOrNot','EverBenched'])
print(df1)

      Education  JoiningYear       City  PaymentTier  Age  Gender  \
0     Bachelors         2017  Bangalore            3   34    Male
1     Bachelors         2013       Pune            1   28  Female
2     Bachelors         2014  New Delhi            3   38  Female
3       Masters         2016  Bangalore            3   27    Male
4       Masters         2017       Pune            3   24    Male
...         ...          ...        ...          ...  ...     ...
4648  Bachelors         2013  Bangalore            3   26  Female
4649    Masters         2013       Pune            2   37    Male
4650    Masters         2018  New Delhi            3   27    Male
4651  Bachelors         2012  Bangalore            3   30    Male
4652  Bachelors         2015  Bangalore            3   33    Male

      ExperienceInCurrentDomain
0                             0
1                             3
2                             2
3                             5
4                             2
...                         ...
4648                          4
4649                          2
4650                          5
4651                          2
4652                          4

[4653 rows x 7 columns]

In [47]:
df['rank'] = df['Age'].rank(ascending=False)
print(df[['Age', 'rank']].head())

   Age    rank
0   34   954.5
1   28  2168.5
2   38   415.5
3   27  2796.0
4   24  4364.0

In [48]:
df.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot,rank
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864,2327.000000
std,1.863377,0.561435,4.826087,1.558240,0.475047,1337.071592
min,2012.000000,1.000000,22.000000,0.000000,0.000000,41.500000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000,1212.500000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000,2168.500000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000,3431.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000,4629.000000

In [52]:
print(df['City'].unique())
print(df['City'].nunique())
print(df['Age'].unique())
print(df['Age'].nunique())

['Bangalore' 'Pune' 'New Delhi']
3
[34 28 38 27 24 22 23 37 32 39 29 30 36 31 25 26 40 35 33 41]
20

In [54]:
df5=df.rename(columns={'Age':'Old', 'City':'Town'})
print(df5.head())

   Education  JoiningYear       Town  PaymentTier  Old  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   ExperienceInCurrentDomain  LeaveOrNot    rank
0                          0           0   954.5
1                          3           1  2168.5
2                          2           0   415.5
3                          5           1  2796.0
4                          2           1  4364.0

In [55]:
df6=df.sort_values(by='Age')
print(df6.head())

      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4069    Masters         2013  New Delhi            2   22    Male         Yes
4539  Bachelors         2014  Bangalore            3   22  Female          No
4048  Bachelors         2014  Bangalore            3   22    Male          No
4070  Bachelors         2015       Pune            1   22  Female          No
4561  Bachelors         2013  Bangalore            3   22    Male          No

      ExperienceInCurrentDomain  LeaveOrNot    rank
4069                          0           1  4629.0
4539                          0           0  4629.0
4048                          0           0  4629.0
4070                          0           1  4629.0
4561                          0           1  4629.0